name: Danger

on: [pull_request]

jobs:
  buildsh:
    env:
        DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
    strategy:
      matrix:
        mode: [danger]
        include:
          - mode: danger
            name: Run Danger
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v1
    - name: Run build script
      run: ./build.sh ${{ matrix.mode }}
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
